### ISSUE TITLE
leaf icons not showing when you set content in code

### ISSUE THREAD

**Issue by rodw65** [daredevel/jquery-tree#39]
I really love your jquery tree but am having a problem.

When I set the contents of the <div> using the innetHTML property in javascript I dont see the tree leaf icons that allow me to collapse. The tree works fine and does the correct actions when checking.  

    document.getElementById("layer_list1").innerHTML = "<ul><li class='collapsed'><input type='checkbox'><span>Node 1</span><ul><li class='collapsed'><input type='checkbox'><span>Node 1.1</span><ul><li class='collapsed'><input type='checkbox'><span>Node 1.1.1</span></ul></ul>";

Any suggestions.

**Comment by daredevel** [comment]
You should use addNode method. It should create complete node element.
