### ISSUE TITLE
How to get selected nodes

### ISSUE THREAD

**Issue by Abel-Liu** [daredevel/jquery-tree#40]
It does not work in demo(http://htmlpreview.github.io/?https://github.com/daredevel/jquery-tree/blob/master/index.html)

**Comment by daredevel** [comment]
Can you explain, please?

**Comment by Abel-Liu** [comment]
![image](https://cloud.githubusercontent.com/assets/7625589/6893635/1c6060dc-d701-11e4-97f1-576ded12b226.png)

Can't get selected items.

**Comment by daredevel** [comment]
I can't see any selected item in this image.

Please, click on a node label and try again.

**Comment by Abel-Liu** [comment]
Please, I just show you where the problem is, I am sure clicked. Did you try that?
Thank you for help.

**Comment by daredevel** [comment]
Yes, I just checked when you opened issue. Now I try again and this is the result:
![Screen](https://cloud.githubusercontent.com/assets/342634/6894372/7f340d7a-d6d5-11e4-8ac5-ab09cd34d620.png)

Which browser are you using? Which kind of error you get in browser console?

**Comment by Abel-Liu** [comment]
I think I find the reason. You know Great Firewall of China? 

![image](https://cloud.githubusercontent.com/assets/7625589/6894855/4edfe28e-d70c-11e4-9e1d-f6e7d7a1d104.png)

**Comment by daredevel** [comment]
No, I don't know, but I can suppose...

Can I close the issue? Or you think I can do someting to fix?

**Comment by Abel-Liu** [comment]
Just close, it's not about you. We can't visit some websites under the "GFW".
Thank you again.

**Comment by daredevel** [comment]
Ok.

You are welcome. Bye.
