### ISSUE TITLE
Retrieve only checked nodes & not parents or root

### ISSUE THREAD

**Issue by sandeshbhoir** [daredevel/jquery-tree#50]
I have used `<input type="checkbox" name="chk[]" value='1' />` in my HTML form

But after I submit my form along with child node value I also get parent node value in my post data.

I need only selected checkbox values.

How do I get that ??

**Comment by daredevel** [comment]
Input elements into form element has standard HTML behavior.

Please look at https://www.w3schools.com/tags/att_input_checked.asp for more informations.
