### ISSUE TITLE
CheckAll with lazy loading

### ISSUE THREAD

**Issue by karan-chauhan** [daredevel/jquery-tree#51]
is there any demo of checkAll / uncheckAll with lazy loading.?

**Comment by daredevel** [comment]
Hi @karan-chauhan,
can you explain what exact do you mean? CheckAll / UncheckAll has no effects on data loading.

**Comment by karan-chauhan** [comment]
Hi @daredevel ,
Thanks for your quick response. 
Actually, i am using jquery-tree with lazy loading functionality. And i want to implement Check All and Uncheck All functionality with my custom buttons. But i don't know how to bind CheckAll / UncheckAll functionality with given buttons. Following is the code that i am using for making tree;
var options = {
                collapseUiIcon:'ui-icon-plus',
                expandUiIcon:'ui-icon-minus',
                lazyLoading: true,
                nodesLazyUrl: 'http://url-for-child-nodes',
                nodesInitUrl: 'http://url-for-parent-nodes'
            };
$('#tree').tree(options);

**Comment by daredevel** [comment]
To bind checkAll/uncheckAll method to your custom buttons, you can use something like following:
`
$('#tree-checkAll').click(function(){
    $('#tree div').tree('checkAll');
});
$('#tree-uncheckAll').click(function(){
    $('#tree div').tree('uncheckAll');
});
`

**Comment by karan-chauhan** [comment]
Thanks @daredevel . 
Its working like charm.
